In [19]:
import numpy as np
data = np.load( "../data/MSL/MSL_test.npy")
label = np.load( "../data/MSL/MSL_test_label.npy")
train = np.load( "../data/MSL/MSL_train.npy")
print(data)
print(len(data))
print(len(data[0]))

# print(train)
print(len(train))
print(len(train[0]))

print(label)
print(len(label))

[[-0.94695788  0.          0.         ...  0.          0.
   0.        ]
 [-0.94227769  0.          0.         ...  0.          0.
   0.        ]
 [-0.93603744  0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.50122056  0.          0.         ...  0.          0.
   0.        ]
 [ 0.50122056  0.          0.         ...  0.          0.
   0.        ]
 [-0.95421168  0.          0.         ...  0.          0.
   0.        ]]
73729
55
58317
55
[False False False ... False False False]
73729


In [20]:
import pandas as pd

train_data_origin = pd.read_excel(( 'dataset/charger/charger_train.xlsx'), header=3, usecols=['开始SOC', '结束SOC', '充电时长（分钟）', '尖电量（kWh）', '峰电量（kWh）', '平电量（kWh）', '低谷电量（kWh）', '总电量（kWh）', '应付（元）'], na_values='#N').to_numpy()
test_data_origin = pd.read_excel(( 'dataset/charger/charger_test.xlsx'), header=3, usecols=['开始SOC', '结束SOC', '充电时长（分钟）', '尖电量（kWh）', '峰电量（kWh）', '平电量（kWh）', '低谷电量（kWh）', '总电量（kWh）', '应付（元）'], na_values='#N').to_numpy()

np.save('dataset/charger/charger_train.npy', train_data_origin)
np.save('dataset/charger/charger_test.npy', test_data_origin)
print(train_data_origin)
print(len(train_data_origin))
print(len(train_data_origin[0]))

print(len(test_data_origin))

[[4.1000e+01 1.0000e+02 1.2452e+02 ... 2.7837e+02 2.7837e+02 2.0042e+02]
 [3.7000e+01 1.0000e+02 1.2300e+02 ... 2.9302e+02 2.9302e+02 2.1098e+02]
 [7.5000e+01 1.0000e+02 7.0230e+01 ... 1.2786e+02 1.2786e+02 9.2060e+01]
 ...
 [4.2000e+01 4.2000e+01 8.7000e-01 ... 1.6000e+00 1.6000e+00 1.1200e+00]
 [3.2000e+01 3.2000e+01 7.0000e-02 ... 0.0000e+00 4.0000e-02 4.0000e-02]
 [4.8000e+01 4.8000e+01 2.3000e-01 ... 0.0000e+00 1.2000e-01 1.2000e-01]]
460
9
269


In [3]:
import numpy as np
import pandas as pd


data = pd.read_excel(( 'dataset/charger/charger1.xlsx'),  na_values='#N')


# 提取标签列
print(data.head())

labels = data['stop_reason'].values

# 提取除标签外的特征数据
features = data.drop(columns=['stop_reason']).to_numpy()

# 显示一些信息确保数据加载正确
print("标签数组维度:", labels.shape)
print("特征数组维度:", features.shape)

# 随机打乱数据
# np.random.shuffle(charge1)

# 计算分割点
split_index = int(0.8 * len(features))  # 20%的数据用于测试集

# 分割数据
train_data = features[:split_index]
test_data = features[split_index:]
test_data_label = labels[split_index:]



# np.save('dataset/charger/charger1_test.npy', test_data)
# np.save('dataset/charger/charger1_train.npy', train_data)
# np.save('dataset/charger/charger1_test_label.npy', test_data_label)



      id station_code charging_pile_code charging_gun_code record_index  \
0  91726       000578   0005002000578002  1000005780020001           14   
1  91727       000578   0005002000578002  1000005780020001           15   
2  91728       000578   0005002000578002  1000005780020001           13   
3  91729       000611   0005002000611001  1000006110010002          215   
4  91730       000578   0005002000578002  1000005780020001           12   

                    order_code    user_id  source operator_code  card_balance  \
0  MA005DBW1230601210149420117  MA005DBW1   100.0     MA005DBW1           0.0   
1  MA005DBW1230601210235430117  MA005DBW1   100.0     MA005DBW1           0.0   
2  MA005DBW1230601210042210121  MA005DBW1   100.0     MA005DBW1           0.0   
3  MA005DBW1230601210321180153  MA005DBW1   100.0     MA005DBW1           0.0   
4  MA005DBW1230601210000280096  MA005DBW1   100.0     MA005DBW1           0.0   

   ... electricity charging_duration process_state  throwable_

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt


data = pd.read_excel(( 'dataset/charger/charger1.xlsx'),  na_values='#N')

# 初始化独热编码器
encoder = OneHotEncoder(sparse_output=False)

# 存储编码后的DataFrame
encoded_data = pd.DataFrame()

# for column in data.columns:
column = "station_code"
print(column)
# 检查列是否为非数字类型
if data[column].dtype == 'object':
    # 去重
    unique_values = data[[column]].drop_duplicates()
    
    # 独热编码
    encoded = encoder.fit_transform(unique_values)
    
    
    # 转换编码结果为DataFrame，并添加合适的列名
    encoded_df = pd.DataFrame(encoded, columns=[f"{column}_{cat}" for cat in encoder.categories_[0]])
    
    # 将编码结果加入到结果DataFrame
    encoded_data = pd.concat([encoded_data, encoded_df], axis=1)

# 应用PCA
pca = PCA(n_components=2)  # 降低到2维
X_pca = pca.fit_transform(encoded_data)


# 可视化结果
plt.figure(figsize=(8, 6))
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y)
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA of Combined Dataset')
plt.legend(*scatter.legend_elements(), title="Classes")
plt.show()

# 显示编码后的结果
print("编码后的数据:")
print(encoded_data)

# 显示原始数据
print("原始数据:")
print(data)




station_code
编码后的数据:
    station_code_0.00  station_code_000001  station_code_000108  \
0                 0.0                  0.0                  0.0   
1                 0.0                  0.0                  0.0   
2                 0.0                  0.0                  0.0   
3                 0.0                  0.0                  0.0   
4                 0.0                  0.0                  0.0   
..                ...                  ...                  ...   
87                0.0                  0.0                  0.0   
88                0.0                  0.0                  0.0   
89                0.0                  0.0                  0.0   
90                1.0                  0.0                  0.0   
91                0.0                  0.0                  0.0   

    station_code_000111  station_code_000209  station_code_000210  \
0                   0.0                  0.0                  0.0   
1                   0.0             

In [4]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

# 加载数据集（这里使用Iris数据集作为示例，实际上Iris数据集不含分类特征，此处仅为演示）
data = load_iris()
X = data.data
y = data.target

# 假设将y转换为分类特征（实际操作中应根据数据情况进行）
df = pd.DataFrame(X, columns=data.feature_names)
df['species'] = pd.Categorical.from_codes(y, categories=data.target_names)

# 独热编码
encoder = OneHotEncoder(sparse_output=False)
X_encoded = encoder.fit_transform(df[['species']])  # 只对species列进行编码

# 合并编码后的数据与原始数据
X_combined = pd.concat([df.drop(columns=['species']), pd.DataFrame(X_encoded, columns=encoder['species'])], axis=1)

# 应用PCA
pca = PCA(n_components=2)  # 降低到2维
X_pca = pca.fit_transform(X_combined)

# 可视化结果
plt.figure(figsize=(8, 6))
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y)
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA of Combined Dataset')
plt.legend(*scatter.legend_elements(), title="Classes")
plt.show()


TypeError: 'OneHotEncoder' object is not subscriptable